// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Horme.API.Data;

#nullable disable

namespace Horme.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Horme.API.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobPostingUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OfferedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferrerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Horme.API.Models.ApplicationStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationStages");
                });

            modelBuilder.Entity("Horme.API.Models.DailyActivity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "Date");

                    b.ToTable("DailyActivities");
                });

            modelBuilder.Entity("Horme.API.Models.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Milestones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111001"),
                            Description = "Sent your first application",
                            Name = "First Application Sent",
                            Slug = "first-application"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111002"),
                            Description = "Sent 10 applications",
                            Name = "10 Applications",
                            Slug = "ten-applications"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111003"),
                            Description = "Sent 25 applications",
                            Name = "25 Applications",
                            Slug = "twenty-five-applications"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111004"),
                            Description = "Received your first response",
                            Name = "First Response",
                            Slug = "first-response"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111005"),
                            Description = "Booked your first interview",
                            Name = "First Interview Booked",
                            Slug = "first-interview"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111006"),
                            Description = "Completed 5 interview stages",
                            Name = "5 Interviews Completed",
                            Slug = "five-interviews"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111007"),
                            Description = "Received your first job offer",
                            Name = "First Offer",
                            Slug = "first-offer"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111008"),
                            Description = "Logged activity for 7 days straight",
                            Name = "7-Day Streak",
                            Slug = "streak-7"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111009"),
                            Description = "Logged activity for 14 days straight",
                            Name = "14-Day Streak",
                            Slug = "streak-14"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111010"),
                            Description = "Logged activity for 30 days straight",
                            Name = "30-Day Streak",
                            Slug = "streak-30"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111011"),
                            Description = "Hit your weekly application target",
                            Name = "Weekly Target Hit",
                            Slug = "weekly-target"
                        });
                });

            modelBuilder.Entity("Horme.API.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinalApplicationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinalInterviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinalOfferCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FinalResponseRate")
                        .HasColumnType("REAL");

                    b.Property<int?>("FinalStreakDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Goal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeklyTarget")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Horme.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Horme.API.Models.UserMilestone", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "MilestoneId", "SeasonId");

                    b.HasIndex("MilestoneId");

                    b.ToTable("UserMilestones");
                });

            modelBuilder.Entity("Horme.API.Models.Application", b =>
                {
                    b.HasOne("Horme.API.Models.Season", "Season")
                        .WithMany("Applications")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Horme.API.Models.ApplicationStage", b =>
                {
                    b.HasOne("Horme.API.Models.Application", "Application")
                        .WithMany("Stages")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Horme.API.Models.DailyActivity", b =>
                {
                    b.HasOne("Horme.API.Models.User", "User")
                        .WithMany("DailyActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horme.API.Models.Season", b =>
                {
                    b.HasOne("Horme.API.Models.User", "User")
                        .WithMany("Seasons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horme.API.Models.UserMilestone", b =>
                {
                    b.HasOne("Horme.API.Models.Milestone", "Milestone")
                        .WithMany("UserMilestones")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Horme.API.Models.User", "User")
                        .WithMany("UserMilestones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horme.API.Models.Application", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Horme.API.Models.Milestone", b =>
                {
                    b.Navigation("UserMilestones");
                });

            modelBuilder.Entity("Horme.API.Models.Season", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Horme.API.Models.User", b =>
                {
                    b.Navigation("DailyActivities");

                    b.Navigation("Seasons");

                    b.Navigation("UserMilestones");
                });
#pragma warning restore 612, 618
        }
    }
}
